spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/fitness_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true