server:
  port: 8080

spring:
  application:
    name: fitness-backend

  datasource:
    url: jdbc:mysql://localhost:3306/fitness_db
    username: dev
    password: N1c0l45.,
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect